Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,5 +13,5 @@ jobs:
         run: echo "this workflow ran successfully for this particular action"
 
       - name: Simulating error
-        run: echo "error taking place": exit 1
+        run: echo "error taking place"; exit 1
 
