Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,6 +12,6 @@ jobs:
       - name: Run a sample GitHub action
         run: echo "this workflow ran successfully for this particular action"
 
-      - name: Simulating error
-        run: echo "error taking place"; exit 1
+      # - name: Simulating error
+      #   run: echo "error taking place"; exit 1
 
